In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
df = pd.read_csv('suv_data.csv')
X = df.drop(columns=['Purchased'])
y = df['Purchased']
X = pd.get_dummies(X, drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
k = 5
knn_model = KNeighborsClassifier(n_neighbors=k)
knn_model.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7166666666666667


In [4]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_classification
X, _ = make_classification(n_samples=100, n_features=4, n_clusters_per_class=1,
random_state=42)
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)
print("Cluster Centers:\n", kmeans.cluster_centers_)

Cluster Centers:
 [[ 0.54995517  0.28524553  0.96163041 -1.04670366]
 [ 1.23798946  0.60635612  2.00231725  1.91433481]
 [ 0.2373546   0.11577163  0.38170444  0.42466382]]
