In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
bnotes = pd.read_csv("banknote-authentication - banknote-authentication.csv")
x = bnotes.drop('class', axis=1)  
y = bnotes['class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
activations = ['relu', 'logistic', 'tanh', 'identity']
for activation in activations:
    print(f"\nTraining MLPClassifier with activation function: {activation}")
    mlp = MLPClassifier(max_iter=500, activation=activation)
    mlp.fit(x_train, y_train)
    pred = mlp.predict(x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, pred))
    print("\nClassification Report:")
    print(classification_report(y_test, pred))



Training MLPClassifier with activation function: relu
Confusion Matrix:
[[150   0]
 [  0 125]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       125

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


Training MLPClassifier with activation function: logistic
Confusion Matrix:
[[149   1]
 [  0 125]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       150
           1       0.99      1.00      1.00       125

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


Training MLPClassifier with activation function: tanh
Confusion Matrix:
[[150   0]
 [  0 125]]

Class